import * as assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';

import { AppError, ErrorCode } from '../errors.js';
import type { Result } from '../result.js';
import { createFilesystemAdapter } from '../storage/index.js';
import type { StorageAdapter } from '../storage/index.js';

import { generateGithubActionsWorkflow, generateWorkflowContent } from './github-actions.js';

let projectRoot = '';

beforeEach(async () => {
  projectRoot = path.join(os.tmpdir(), randomUUID());
  await fs.mkdir(projectRoot, { recursive: true });
});

afterEach(async () => {
  await fs.rm(projectRoot, { recursive: true, force: true });
});

void describe('ci/github-actions', () => {
  void it('does generate workflow content with expected core actions and secret', () => {
    const content = generateWorkflowContent({
      envs: ['staging', 'production'],
    });

    assert.match(content, /actions\/checkout@v4/u);
    assert.match(content, /\$\{\{ secrets\.ENVLT_KEY \}\}/u);
    assert.match(content, /Check environment variables \(staging\)/u);
    assert.match(content, /Check environment variables \(production\)/u);
  });

  void it('does generate one check step per env', () => {
    const envs = ['development', 'staging', 'production'];
    const content = generateWorkflowContent({ envs });

    const stepCount = (content.match(/Check environment variables \(/gu) ?? []).length;
    assert.equal(stepCount, envs.length);
  });

  void it('does include provided node version', () => {
    const content = generateWorkflowContent({
      envs: ['staging'],
      nodeVersion: '18',
    });

    assert.match(content, /node-version: '18'/u);
  });

  void it('does write generated workflow to .github/workflows/envlt.yml', async () => {
    const adapter = createFilesystemAdapter(projectRoot);
    const result = await generateGithubActionsWorkflow(
      ['staging', 'production'],
      projectRoot,
      adapter,
    );
    assert.equal(result.ok, true);

    const outputPath = path.join(projectRoot, '.github', 'workflows', 'envlt.yml');
    const written = await fs.readFile(outputPath, 'utf8');

    assert.match(written, /^# Generated by envlt/u);
    assert.match(written, /name: envlt/u);
    assert.match(written, /jobs:/u);
    assert.match(written, /envlt check --env staging/u);
    assert.match(written, /envlt check --env production/u);
  });

  void it('does allow overriding workflow name and node version when writing file', async () => {
    const adapter = createFilesystemAdapter(projectRoot);
    const result = await generateGithubActionsWorkflow(['preview'], projectRoot, adapter, {
      workflowName: 'custom-workflow',
      nodeVersion: '18',
    });
    assert.equal(result.ok, true);

    const outputPath = path.join(projectRoot, '.github', 'workflows', 'envlt.yml');
    const written = await fs.readFile(outputPath, 'utf8');
    assert.match(written, /name: custom-workflow/u);
    assert.match(written, /node-version: '18'/u);
  });

  void it('does return error when adapter write fails', async () => {
    const failingAdapter: StorageAdapter = {
      read: async (): Promise<Result<Buffer>> =>
        Promise.resolve({ ok: true, value: Buffer.alloc(0) }),
      write: async (): Promise<Result<void>> =>
        Promise.resolve({
          ok: false,
          error: new AppError(ErrorCode.STORAGE_WRITE_ERROR, 'write failed'),
        }),
      exists: async (): Promise<Result<boolean>> => Promise.resolve({ ok: true, value: false }),
      delete: async (): Promise<Result<void>> => Promise.resolve({ ok: true, value: undefined }),
    };

    const result = await generateGithubActionsWorkflow(['staging'], projectRoot, failingAdapter);
    assert.equal(result.ok, false);
  });
});
