import * as path from 'node:path';

import { ENV_NAME_PATTERN } from '../constants.js';
import { AppError, ErrorCode } from '../errors.js';
import { err, ok, type Result } from '../result.js';
import type { StorageAdapter } from '../storage/index.js';

export type WorkflowOptions = {
  readonly envs: readonly string[];
  readonly workflowName?: string;
  readonly nodeVersion?: string;
};

const GENERATED_HEADER = '# Generated by envlt — do not edit manually';
const DEFAULT_WORKFLOW_NAME = 'envlt';
const DEFAULT_NODE_VERSION = '20';
const ENVLT_SECRET_NAME = 'ENVLT_KEY';
const WORKFLOW_RELATIVE_PATH = path.join('.github', 'workflows', 'envlt.yml');
const NODE_VERSION_PATTERN = /^\d+(?:\.\d+){0,2}$/u;
const WORKFLOW_NAME_PATTERN = /^[A-Za-z0-9 _.-]{1,100}$/u;

function envltSecretRef(secretName: string): string {
  return `\${{ secrets.${secretName} }}`;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/gu, `'"'"'`)}'`;
}

function yamlSingleQuoted(value: string): string {
  return `'${value.replace(/'/gu, "''")}'`;
}

function assertValidEnvName(envName: string): void {
  if (!ENV_NAME_PATTERN.test(envName)) {
    throw new AppError(
      ErrorCode.ENVFILE_INVALID_ENV_NAME,
      `Invalid environment name for workflow generation: ${envName}`,
    );
  }
}

function assertValidNodeVersion(nodeVersion: string): void {
  if (!NODE_VERSION_PATTERN.test(nodeVersion)) {
    throw new AppError(
      ErrorCode.CONFIG_INVALID,
      `Invalid node version for workflow generation: ${nodeVersion}`,
    );
  }
}

function assertValidWorkflowName(workflowName: string): void {
  if (!WORKFLOW_NAME_PATTERN.test(workflowName)) {
    throw new AppError(
      ErrorCode.CONFIG_INVALID,
      `Invalid workflow name for workflow generation: ${workflowName}`,
    );
  }
}

function generateCheckStep(envName: string): string {
  assertValidEnvName(envName);
  return [
    `      - name: Check environment variables (${envName})`,
    '        env:',
    `          ${ENVLT_SECRET_NAME}: ${envltSecretRef(ENVLT_SECRET_NAME)}`,
    `        run: envlt check --env ${shellQuote(envName)}`,
  ].join('\n');
}

export function generateWorkflowContent(options: WorkflowOptions): string {
  const workflowName = options.workflowName ?? DEFAULT_WORKFLOW_NAME;
  const nodeVersion = options.nodeVersion ?? DEFAULT_NODE_VERSION;

  assertValidWorkflowName(workflowName);
  assertValidNodeVersion(nodeVersion);

  const envSteps = options.envs.map((envName) => generateCheckStep(envName)).join('\n\n');

  return [
    GENERATED_HEADER,
    `name: ${yamlSingleQuoted(workflowName)}`,
    '',
    'on:',
    '  push:',
    '    branches: [main, master]',
    '  pull_request:',
    '',
    'jobs:',
    '  check:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '',
    '      - name: Setup Node.js',
    '        uses: actions/setup-node@v4',
    '        with:',
    `          node-version: ${yamlSingleQuoted(nodeVersion)}`,
    '',
    '      - name: Install envlt',
    '        run: npm install -g envlt',
    '',
    envSteps,
    '',
  ].join('\n');
}

export async function generateGithubActionsWorkflow(
  envs: readonly string[],
  projectRoot: string,
  adapter: StorageAdapter,
  options: Partial<WorkflowOptions> = {},
): Promise<Result<void>> {
  const workflowPath = path.resolve(projectRoot, WORKFLOW_RELATIVE_PATH);
  let workflowContent: string;

  try {
    workflowContent = generateWorkflowContent({
      envs,
      ...(options.workflowName !== undefined ? { workflowName: options.workflowName } : {}),
      ...(options.nodeVersion !== undefined ? { nodeVersion: options.nodeVersion } : {}),
    });
  } catch (error: unknown) {
    if (error instanceof AppError) {
      return err(error);
    }

    return err(
      new AppError(ErrorCode.CONFIG_INVALID, 'Invalid workflow generation options.', error),
    );
  }

  const writeResult = await adapter.write(workflowPath, Buffer.from(workflowContent, 'utf8'));
  if (!writeResult.ok) {
    return err(
      new AppError(
        ErrorCode.STORAGE_WRITE_ERROR,
        'Failed to generate GitHub Actions workflow.',
        writeResult.error,
      ),
    );
  }

  return ok(undefined);
}
